### ISSUE TITLE
Some Examples Of Useage

### ISSUE THREAD

**Issue by alireza8101** [arazmj/GoCache#1]
Hey there @arazmj, I'm interested in using the GoCache you've created, but am a little unsure about how to actually go about using it after it's set up.
Any help would be greatly appreciated,
Thanks.

**Comment by arazmj** [comment]
Thank you for reaching out to us. I will add examples from a set languages. What programming language do you use?

**Comment by alireza8101** [comment]
Nodejs

> Thank you for reaching out to us. I will add examples from a set languages. What programming language do you use?

Nodejs

**Comment by arazmj** [comment]
I have added NodeJS example in the 'Examples' directory.
