### ISSUE TITLE
Provide posting values by body

### ISSUE THREAD

**Issue by alireza8101** [arazmj/GoCache#2]
If we have a big value it would probably not fit into a URL. Would you also provide Posting value by the body as well?

**Comment by arazmj** [comment]
Thank you for your feedback. We just fixed the issue. 
Please check this [commit](https://github.com/arazmj/GoCache/commit/eac92c47c645bbb4ec492c02948710f7900e5804)

**Comment by alireza8101** [comment]
> Thank you for your feedback. We just fixed the issue.
> Please check this [commit](https://github.com/arazmj/GoCache/commit/eac92c47c645bbb4ec492c02948710f7900e5804)

Perfect!
